# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: 'ResearchOrganization'
    local_business_type: ''
    org_name: 'Campus-wide Computing Research Division, Information Technology Center, The University of Tokyo'
    description: 'World Wide Web of Kenichiro Ito Office at CCR, ITC, The University of Tokyo. Main research topic includes but not limited to Internet of Things (IoT), Virtual Reality (VR), Augmented Reality (AR), Mixed Reality (MR), x Reality, Metaverse, Human-Computer Interaction (HCI), Human-Machine Interface (HMI), User Interface (UI), User Experience (UX), Systems Engineering (SE), System of Systems (SoS)'
    twitter: 'ikenichiro'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: false
    align: l
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} Kenichiro Ito. This work is mostly licensed under {license} except for published materials such as Journal Papers or Conference Papers which follows the license from the publisher.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '15:04:05 MST'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/ikenichiro/ito-ecc-website'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    wowchemy:
      min_length: 1
      threshold: 0.3
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
